version: '2.0'
services:
    c:
        restart: always
        build: .
        ports:
            - 8099:8099
        environment:
            HOST: 0.0.0.0
            PORT: 8099
        volumes:
            - ./data:/data


